config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
  get 'properties/index'
  end

  namespace :admin do
  get 'properties/new'
  end

  namespace :admin do
  get 'properties/edit'
  end

  namespace :admin do
  get 'properties/show'
  end

  namespace :designer do
    get 'home/index'
    resource :product
    get 'products/index'
  end

  namespace :admin do
    get 'home/user'
    get 'home/index'
    get 'home/login'
    get 'home/about'
    get 'home/help'
    get 'home/contact_us'
    root 'home#login'

    get 'products/delete'

    get 'properties/product_property'

    resources :properties

    resources :orders
    resources :products

    get 'resources/configure'
    get 'resources/global_header'
    get 'resources/global_body'
    get 'resources/global_footer'
    get 'resources/new_global'
    get 'resources/product'
    get 'resources/check'
    get 'resources/product_picture'

    get 'resources/new_product'

    resources :resources

    get 'users/show'
    get 'users/delete'
    get 'users/edit'
    get 'users/new'
    get 'users/index'

  end

  resources :orders
  resources :line_items
  resources :carts
  resources :products
  get 'store/checkout'
  get 'store/empty_cart'
  get 'store/display_cart'
  get 'store/add_to_cart'
  get 'store/index'
  get 'home/about'

  devise_for :users

   root 'store#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :properties
  has_many :resources
  has_many :carts, :through => :line_items

  mount_uploader :image_url,ImageUploader

 # before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :description,  :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :title, :uniqueness => true
  #validates :image_url, :format => {
  #                        :with=> %r{\.(gif|jpg|png)$}i,
  #                        :message => 'must be a URL for GIF, JPG, or PNG image.'
  #                    }
  def self.salable_items
    Product.all
  end

  private

  #ensure that there are no line items referencing this product
  # def ensure_not_referenced_by_any_line_item
  #   if line_items.empty?
  #     return true
  #   else
  #     errors.add(:base, 'Line Items present')
  #     return false
  #   end
  # end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @count=0
    render :layout => 'admin/layouts/application'
  end

  # GET /products/1
  # GET /products/1.json
  def show
    render :layout => 'admin/layouts/application'
  end

  # GET /products/new
  def new
    @product = Product.new
    render :layout => 'admin/layouts/application'
  end

  # GET /products/1/edit
  def edit
    render :layout => 'admin/layouts/application'
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_products_path, notice: '商品成功创建.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to controller:'admin/products',action:'show',id:@product.id, notice: 'Product was successfully updated.' }
        format.json { render 'admin/products/show', status: :ok, location: @product }
      else
        format.html { render 'admin/products/edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
  end

  # DELETE /products/1
  # DELETE /products/1.js

  def destroy
    @product.destroy
    redirect_to admin_products_url, notice: '成功删除'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id].to_i)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:title, :description, :image_url, :price, :designer)
  end


end

app/controllers/designer/products_controller.rb
class Designer::ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
   # @products = Product.where(:designer => current_user)
    @products = Product.all
    render :layout => 'designer/layouts/application'
  end

  def new
    @product = Product.new
  end

  def show
    render :layout => 'designer/layouts/application'
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.designer = current_user.username
    @product.save
    redirect_to :action => 'edit', :id => Product.last
    #    respond_to do |format|
#      if @product.save
#        format.html { redirect_to @product, notice: 'Product was successfully created.' }
#        format.json { render :show, status: :created, location: @product }
#      else
#        format.html { render :create }
#        format.json { render json: @product.errors, status: :unprocessable_entity }
#      end
#    end
  end

  def update
    @product.update(product_params)
    redirect_to :action => 'index'
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :image_url, :price)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product.visits = @product.visits + 1;
    @product.save;
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/helpers/designer/products_helper.rb
module Designer::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<div class="ui form">
<%= form_for @product,url: {action:'update',controller:'admin/products'} do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




  <div class="field">
    <%= f.label :商品名称 %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :商品描述 %><br>
    <%= f.text_area :description,:size=>'40x5'%>
  </div>
      <div class="field">
        <%= f.label :设计师 %><br>
        <%= f.text_field :designer %>
      </div>
  <div class="field">
    <%= f.label :上传图片文件 %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :商品价格 %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <button class="ui button" type="submit">确认修改</button>
  </div>
<% end %>
</div>

app/views/admin/products/edit.html.erb
<h2 class="ui top attached header">编辑商品</h2>
<div class="ui attached segment">

  <div class="ui attached segment">
    <div class="ui form segment">
      <%= form_for @product,url: {action:'update',controller:'admin/products',:id=>@product.id } do |f| %>
          <% if @product.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@product.errors.count, 'error') %> 禁止保存:</h2>

                <ul>
                  <% @product.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <div class="field">
            <%= f.label :商品名称 %>
            <%= f.text_field :title %>
          </div>

          <%= f.hidden_field :id,:value=>@product.id %>

          <div class="field">
            <%= f.label :商品描述 %>
            <%= f.text_area :description,:size=>'40x5'%>
          </div>
          <div class="field">
            <%= f.label :设计师 %>
            <%= f.text_field :designer %>
          </div>

          <div class="field">
            <%= f.label :上传图片文件 %>
            <%= f.file_field :image_url,:id=>'carpoolpic2',:onchange=>'changesrc(this)'%>
            <%= f.hidden_field :image_url_cache %>
            <h3>预览：</h3>
            <img src="" alt="" id="prev" height="200" width="340" />
            当前选择文件大小：
            <div id="fileSize"></div>
          </div>

          <div class="field">
            <%= f.label :商品价格 %>
            <%= f.text_field :price %>
          </div>
          <div class="actions">
            <button class="red ui button" type="submit">确认添加</button>
            <div class="ui error message"></div>
          </div>
      <% end %>
    </div>
  </div>
</div>
<br />


<script>
    $(document).ready(function() {
        $('.ui.form')
                .form({
                    fields: {
                        title: {
                            identifier: 'product[title]',
                            rules: [
                                {
                                    type: 'empty',
                                    prompt: '请输入商品名称'
                                }
                            ]
                        },
                        description:{
                            identifier:'product[description]',
                            rules:[
                                {
                                    type:'empty',
                                    prompt:'请输入商品描述'
                                }
                            ]
                        },
                        designer: {
                            identifier: 'product[designer]',
                            rules: [
                                {
                                    type: 'empty',
                                    prompt: '请选择一名设计师'
                                }
                            ]
                        },
                        price:{
                            identifier:'product[price]',
                            rules:[
                                {
                                    type:'regExp[/^([1-9]{1}[0-9]{0,10}.)?[0-9]{0,10}$/]',
                                    prompt:'请输入正确的价格'
                                }
                            ]
                        }
                    }
                })
    });
</script>
<script type="text/javascript">

    var flag = true;
    /**预览图片*/
    function changesrc(sender) {
        sender_id = sender.id;
        var imgSrc = document.getElementById(sender_id).value;
        var t = document.getElementById(sender_id);
        if (imgSrc == "") {
            flag = false;
            return false;
        }
        if (checkType('jpg,bpm,png,jpeg',imgSrc) == false) {
            document.getElementById(sender_id).value = "";
            alert("图片格式不正确!");
            flag = false;
            return false; //如果不是jpg返回false
        } else {
            var imgs = document.createElement("img");
            imgs.src = imgSrc;

            ////判断图片大小
            if (fileChange(sender) > 1000 * 1024) {
                alert("图片大小不能超过 1000 KB!");
                flag = false;
                return false; //超过50K返回false
            }
            ////
            flag = true;
        }
        if (isFirefox = navigator.userAgent.indexOf("IE") > 0) {
            document.getElementById("prev").src = imgSrc;
        }else{
            document.getElementById("prev").src = window.URL.createObjectURL(t.files[0]);
        }
    }

    /**判断图片类型*/
    function checkType(types,imgSrc){
        var typeArr = types.split(",");
        var rg;
        var length = typeArr.length;
        var sb=new StringBuilder();

        for(var i = 0, len = length; i < len; i++) {
            rg = '/(.*?)\.'+typeArr[i]+'$/.test(imgSrc.toLowerCase())';
            if(i+1 != length)
                rg = rg + " || ";
            sb.append(rg);
        }
        return eval(sb.toString());
    }

    /**够造StringBuilder*/
    function StringBuilder(){
        this._strings_=new Array;
    }
    StringBuilder.prototype.append=function(str){
        this._strings_.push(str);
    };
    StringBuilder.prototype.toString=function(){
        return this._strings_.join("");
    };



    //文件大小
    var isIE = /msie/i.test(navigator.userAgent) && !window.opera;
    var sizeLabel = ["B", "KB", "MB", "GB"];
    //获取文件大小
    function fileChange(target) {

        var fileSize = 0;

        if (isIE && !target.files) {
            var filePath = target.value;
            var fileSystem = new ActiveXObject("Scripting.FileSystemObject");
            var file = fileSystem.GetFile (filePath);
            fileSize = file.Size;
        } else {
            fileSize = target.files[0].size;
        }
        displayFileSize(fileSize);
        return fileSize;
    }

    //显示文件大小
    function displayFileSize(size) {
        var fileSize = document.getElementById("fileSize");
        fileSize.innerHTML = calFileSize(size);
    }

    //计算文件大小 返回格式化后的字符串 xx kb  xx Mb
    function calFileSize(size) {
        for (var index = 0; index < sizeLabel.length; index++) {

            if (size < 1024) {
                return round(size, 2) + sizeLabel[index];
            }

            size = size / 1024;
        }

        return round(size, 2) + sizeLabel[index];
    }

    function round(number, count) {
        return Math.round(number * Math.pow(10, count)) / Math.pow(10, count);
    }

</script>


<%= link_to '显示',admin_product_path(@product) ,class:'compact ui button' %> |
<%= link_to '返回', admin_products_path,class:'compact ui button'%>
<br /><br />

app/views/admin/products/index.html.erb
<h1 class="ui top attached header">商品展示</h1>
<div class="ui attached segment">
  <table class="ui selectable inverted table">
    <thead>
    <tr>
      <th>编号</th>
      <th>商品名称</th>
      <th>价格</th>
      <th>设计师</th>
      <th>操作</th>
    </tr>
    </thead>
    <tbody>
    <% @count = 0 %>
    <% @products.each do |product| %>
    <tr>
      <div id=<%= @count %>>
      <% @count+=1 %>
      <td><%= @count %></td>
      <td><%= product.title %></td>
      <td><%= product.price %></td>
      <td><%= product.designer %></td>
        <td><%= link_to '显示',admin_product_path(product),:class =>'mini inverted blue ui button' %>
        <%= link_to '编辑',edit_admin_product_path(product),:class =>'mini inverted blue ui button' %>
          <%= link_to '商品性质',{:controller => 'admin/properties',:action=>'product_property',product_id:product.id},:class=>'mini inverted blue ui button' %>
          <%= link_to '商品图片',{:controller =>'admin/resources',:action => 'product_picture', id:product.id},:class=>'mini inverted blue ui button' %>
          <%= link_to '删除',admin_product_path(product),method: :delete, data: { confirm: '确定要删除该商品吗?' },:class =>'mini inverted red ui button'%>
      </div>
    </tr>
    <% end %>
    </tbody>
  </table>
</div>
<h3 class="ui bottom attached header">展示结束</h3>
<br />

<%= link_to '新增商品',new_admin_product_path,class:'ui secondary button' %>

app/views/admin/products/new.html.erb
<h2 class="ui top attached header">新增商品</h2>
<div class="ui attached segment">

  <div class="ui attached segment">
    <div class="ui form segment">
    <%= form_for @product,url: {action:'create',controller:'admin/products',:id=>@product.id } do |f| %>
        <% if @product.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@product.errors.count, 'error') %> 禁止保存:</h2>

              <ul>
                <% @product.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field">
          <%= f.label :商品名称 %>
          <%= f.text_field :title %>
        </div>

        <%= f.hidden_field :id,:value=>@product.id %>

        <div class="field">
          <%= f.label :商品描述 %>
          <%= f.text_area :description,:size=>'40x5'%>
        </div>
        <div class="field">
          <%= f.label :设计师 %>
          <%= f.text_field :designer %>
        </div>

        <div class="field">
          <%= f.label :上传图片文件 %>
          <%= f.file_field :image_url,:id=>'carpoolpic2',:onchange=>'changesrc(this)'%>
          <%= f.hidden_field :image_url_cache %>

          <h3>预览：</h3>
          <img src="" alt="" id="prev" height="200" width="340" />
          当前选择文件大小：
          <div id="fileSize"></div>
        </div>

        <div class="field">
          <%= f.label :商品价格 %>
          <%= f.text_field :price %>
        </div>
        <div class="actions">
          <button class="red ui button" type="submit">确认添加</button>
          <div class="ui error message"></div>
        </div>
    <% end %>
  </div>
  </div>
</div>
<br />


<script>
    $(document).ready(function() {
        $('.ui.form')
                .form({
                    fields: {
                        title: {
                            identifier: 'product[title]',
                            rules: [
                                {
                                    type: 'empty',
                                    prompt: '请输入商品名称'
                                }
                            ]
                        },
                        description:{
                            identifier:'product[description]',
                            rules:[
                                {
                                    type:'empty',
                                    prompt:'请输入商品描述'
                                }
                            ]
                        },
                        designer: {
                            identifier: 'product[designer]',
                            rules: [
                                {
                                    type: 'empty',
                                    prompt: '请选择一名设计师'
                                }
                            ]
                        },
                        price:{
                            identifier:'product[price]',
                            rules:[
                                {
                                    type:'regExp[/^([0-9]{1,10}.)?[0-9]{0,10}$/]',
                                    prompt:'请输入正确的价格'
                                }
                            ]
                        }
                    }
                })
    });
</script>

<script type="text/javascript">

    var flag = true;
    /**预览图片*/
    function changesrc(sender) {
        sender_id = sender.id;
        var imgSrc = document.getElementById(sender_id).value;
        var t = document.getElementById(sender_id);
        if (imgSrc == "") {
            flag = false;
            return false;
        }
        if (checkType('jpg,bpm,png,jpeg',imgSrc) == false) {
            document.getElementById(sender_id).value = "";
            alert("图片格式不正确!");
            flag = false;
            return false; //如果不是jpg返回false
        } else {
            var imgs = document.createElement("img");
            imgs.src = imgSrc;

            ////判断图片大小
            if (fileChange(sender) > 1000 * 1024) {
                alert("图片大小不能超过 1000 KB!");
                flag = false;
                return false; //超过50K返回false
            }
            ////
            flag = true;
        }
        if (isFirefox = navigator.userAgent.indexOf("IE") > 0) {
            document.getElementById("prev").src = imgSrc;
        }else{
            document.getElementById("prev").src = window.URL.createObjectURL(t.files[0]);
        }
    }

    /**判断图片类型*/
    function checkType(types,imgSrc){
        var typeArr = types.split(",");
        var rg;
        var length = typeArr.length;
        var sb=new StringBuilder();

        for(var i = 0, len = length; i < len; i++) {
            rg = '/(.*?)\.'+typeArr[i]+'$/.test(imgSrc.toLowerCase())';
            if(i+1 != length)
                rg = rg + " || ";
            sb.append(rg);
        }
        return eval(sb.toString());
    }

    /**够造StringBuilder*/
    function StringBuilder(){
        this._strings_=new Array;
    }
    StringBuilder.prototype.append=function(str){
        this._strings_.push(str);
    };
    StringBuilder.prototype.toString=function(){
        return this._strings_.join("");
    };



    //文件大小
    var isIE = /msie/i.test(navigator.userAgent) && !window.opera;
    var sizeLabel = ["B", "KB", "MB", "GB"];
    //获取文件大小
    function fileChange(target) {

        var fileSize = 0;

        if (isIE && !target.files) {
            var filePath = target.value;
            var fileSystem = new ActiveXObject("Scripting.FileSystemObject");
            var file = fileSystem.GetFile (filePath);
            fileSize = file.Size;
        } else {
            fileSize = target.files[0].size;
        }
        displayFileSize(fileSize);
        return fileSize;
    }

    //显示文件大小
    function displayFileSize(size) {
        var fileSize = document.getElementById("fileSize");
        fileSize.innerHTML = calFileSize(size);
    }

    //计算文件大小 返回格式化后的字符串 xx kb  xx Mb
    function calFileSize(size) {
        for (var index = 0; index < sizeLabel.length; index++) {

            if (size < 1024) {
                return round(size, 2) + sizeLabel[index];
            }

            size = size / 1024;
        }

        return round(size, 2) + sizeLabel[index];
    }

    function round(number, count) {
        return Math.round(number * Math.pow(10, count)) / Math.pow(10, count);
    }

</script>



<%= link_to '返回', admin_products_path,class:'compact ui button'%>
<br /><br />

app/views/admin/products/show.html.erb
<div class="ui raised very padded text container segment">
  <h2 class="ui header">商品详细信息显示</h2>
  <p>
    <strong>商品名称:</strong>
    <%= @product.title %>
  </p>

  <p>
    <strong>商品描述:</strong>
    <%= @product.description %>
  </p>

  <p>
    <strong>图片地址:</strong>
    <%= @product.image_url %>
  </p>

  <p>
    <strong>价格:</strong>
    <%= @product.price %>
  </p>
  <%= link_to '编辑', edit_admin_product_path(@product),class:'ui compact button' %> |
  <%= link_to '返回', admin_products_path,class:'ui compact button' %>
</div>
